name: scRNA-seq-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - snakemake=7.32
  - pandas=2.0
  - star=2.7.11a
  - samtools=1.19
  - pip
  - pip:
    - -e .